[package]
name = "crate-example"
version = "0.1.0"
authors = ["nanato12"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
