version: '3'
services:
  rust:
    restart: always
    build: .
    container_name: 'rust1.47.0'
    working_dir: '/home/nanato12/workspace'
    tty: true
    volumes:
      - ./workspace:/home/nanato12/workspace
