version: '3'
services:
  ubuntu:
    restart: always
    build: .
    container_name: 'linuxbrew'
    working_dir: '/home/nanato12/workspace'
    tty: true
    volumes:
      - ./workspace:/home/nanato12/workspace
      - ./.linuxbrew:/home/linuxbrew/.linuxbrew
