# This is a basic workflow to help you get started with Actions

name: Checker

on: [push]

jobs:
  pycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for Python code check
        uses: nanato12/pychecker@master
        with:
          path: './python/workspace'
  gocheck:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for golang code check
        uses: nanato12/gocheck@master
        with:
          path: './golang/workspace/tutorial'
