# This is a basic workflow to help you get started with Actions

name: Pycheck

on: [push]

jobs:
  pycheck:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Python code check
        uses: nanato12/pycheck@master
        with:
          args: flake8 . --show-source --statistics & PID1=$! && black --check . & PID2=$! && wait $PID1 && wait $PID2 && ls -a
