# This is a basic workflow to help you get started with Actions

name: Pycheck

on: [push]

jobs:
  pycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for Python code check
        uses: nanato12/pycheck@v1.0.0
        with:
          path: './python/workspace'
