# This is a basic workflow to help you get started with Actions

name: Lint

on:
  push:
    paths:
      - '*.py'

jobs:
  pycheck:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Python code check
        uses: nanato12/pycheck@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          checkName: 'pycheck'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
